version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: lWords
    restart: always
    environment:
      POSTGRES_USER: lWordsAdmin
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: lWords
    ports:
      - "5555:5432"