// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package parser

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Result struct {
	ID     int32
	UserID pgtype.Int4
	WordID pgtype.Int4
	Grade  pgtype.Int4
}

type Statistic struct {
	ID              int32
	UserID          pgtype.Int4
	LearnedWords    pgtype.Int4
	NotLearnedWords pgtype.Int4
}

type User struct {
	ID        int32
	Username  pgtype.Text
	Password  pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Word struct {
	ID      int32
	Eng     string
	Rus     string
	LearnAt pgtype.Timestamp
}
